export type SourceClass = "official_trust" | "administrator" | "case_agent" | "court" | "government" | "primary_document";

export type SourceRegistryOverride = {
  trustName: string;
  sourceUrl: string;
  sourceClass: SourceClass;
  retrievalNotes: string;
};

// Reviewed no-charge public monitoring routes. Registration is not a claim
// that a source is current or that its content establishes a public fact.
export const SOURCE_REGISTRY_OVERRIDES: Record<string, SourceRegistryOverride> = {
  "a-best-products-asbestos-trust": { trustName: "A-Best Products Asbestos Trust", sourceUrl: "https://www.abestasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; use public documents and notices only." },
  "a-i-corporation-asbestos-bodily-injury-trust": { trustName: "A & I Corporation Asbestos Bodily Injury Trust", sourceUrl: "https://www.aisettlement.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; use public documents and notices only." },
  "a-p-green-apg-asbestos-trust": { trustName: "A.P. Green (APG) Asbestos Trust", sourceUrl: "https://apg.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Official administrator-hosted trust portal reviewed 2026-09-07." },
  "abb-lummus-global-inc-524-g-asbestos-pi-trust": { trustName: "ABB Lummus Global Inc. 524(g) Asbestos PI Trust", sourceUrl: "https://www.abblummustrust.org/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; supplements the filed-report URL in the tracker." },
  "acands-asbestos-settlement-trust": { trustName: "ACandS Asbestos Settlement Trust", sourceUrl: "https://www.acandsasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; use public documents and notices only." },
  "api-inc-asbestos-settlement-trust": { trustName: "API, Inc. Asbestos Settlement Trust", sourceUrl: "https://apiincasbestossettlementtrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; supplements filed-report coverage." },
  "brauer-524-g-asbestos-trust-brauer-supply-company": { trustName: "Brauer 524(g) Asbestos Trust", sourceUrl: "https://www.brauertrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; preserve Wayback evidence separately." },
  "burns-and-roe-personal-injury-settlement-trust": { trustName: "Burns and Roe Personal Injury Settlement Trust", sourceUrl: "https://www.burnsandroetrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; use public documents and notices only." },
  "c-e-thurston-sons-asbestos-trust": { trustName: "C.E. Thurston & Sons Asbestos Trust", sourceUrl: "https://www.thurstonasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; CRMC remains a documented fallback." },
  "christy-refractories-asbestos-pi-trust": { trustName: "Christy Refractories Asbestos PI Trust", sourceUrl: "https://www.christy-trust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; Verus remains a documented fallback." },
  "duro-dyne-asbestos-personal-injury-trust": { trustName: "Duro Dyne Asbestos Personal Injury Trust", sourceUrl: "https://durodyne.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Official administrator-hosted trust portal reviewed 2026-09-07." },
  "fuller-austin-asbestos-settlement-trust": { trustName: "Fuller-Austin Asbestos Settlement Trust", sourceUrl: "https://www.fulleraustintrust.org/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; record future access limitations explicitly." },
  "hercules-chemical-co-asbestos-settlement-trust": { trustName: "Hercules Chemical Co. Asbestos Settlement Trust", sourceUrl: "https://hercules.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Official administrator-hosted trust portal reviewed 2026-09-07." },
  "j-t-thorpe-company-successor-trust-tx": { trustName: "J.T. Thorpe Company Successor Trust (TX)", sourceUrl: "https://thorpe.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Official administrator-hosted trust portal reviewed 2026-09-07." },
  "keene-creditors-trust": { trustName: "Keene Creditors Trust", sourceUrl: "https://www.cpf-inc.com/trusts/keene-trust", sourceClass: "administrator", retrievalNotes: "Official Claims Processing Facility trust page reviewed 2026-09-07." },
  "leslie-controls-inc-asbestos-personal-injury-trust": { trustName: "Leslie Controls Inc. Asbestos PI Trust", sourceUrl: "https://leslie.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Official administrator-hosted trust portal reviewed 2026-09-07." },
  "motors-liquidation-co-gm-asbestos-pi-trust": { trustName: "Motors Liquidation Co. (GM) Asbestos PI Trust", sourceUrl: "https://www.claimsres.com/documents/mlc/", sourceClass: "administrator", retrievalNotes: "Official CRMC document repository reviewed 2026-09-07." },
  "porter-hayden-bodily-injury-trust": { trustName: "Porter Hayden Bodily Injury Trust", sourceUrl: "https://www.porterhaydentrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; Verus is the documented fallback." },
  "rapid-american-asbestos-pi-trust": { trustName: "Rapid-American Asbestos PI Trust", sourceUrl: "https://www.rapidamericanasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal reviewed 2026-09-07; DCPF is the documented fallback." },
  "raytech-raymark-trust": { trustName: "Raytech/Raymark Trust", sourceUrl: "https://www.cpf-inc.com/trusts/raytech-trust/", sourceClass: "administrator", retrievalNotes: "Official Claims Processing Facility trust page reviewed 2026-09-07." },
  "shook-fletcher-asbestos-settlement-trust": { trustName: "Shook & Fletcher Asbestos Settlement Trust", sourceUrl: "https://www.claimsres.com/shook-fletcher/", sourceClass: "administrator", retrievalNotes: "Official CRMC trust page reviewed 2026-09-07." },
  "t-h-agriculture-nutrition-l-l-c-asbestos-personal-injury-trust-than": { trustName: "T-H Agriculture & Nutrition (THAN) Asbestos PI Trust", sourceUrl: "https://www.thanasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; preserve filed-document evidence separately." },
  "united-gilsonite-ugl-asbestos-pi-trust": { trustName: "United Gilsonite (UGL) Asbestos PI Trust", sourceUrl: "https://www.ugltrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; CPF is the documented fallback." },
  "united-states-mineral-products-company-asbestos-pi-settlement-trust": { trustName: "U.S. Mineral Products Company Asbestos PI Settlement Trust", sourceUrl: "https://www.usmineraltrust.com/", sourceClass: "official_trust", retrievalNotes: "Official trust portal lead reviewed 2026-09-07; Verus is the documented fallback." },
  "bondex-specialty-products-holding-corp-trust": { trustName: "Bondex (Specialty Products Holding Corp.) Trust", sourceUrl: "https://www.cpf-inc.com/trusts/bondex-trust", sourceClass: "administrator", retrievalNotes: "Replaces legacy host with TLS hostname mismatch; use the official CPF trust page." },
  "congoleum-plan-trust": { trustName: "Congoleum Plan Trust", sourceUrl: "https://www.congoleumtrust.com/", sourceClass: "official_trust", retrievalNotes: "Replaces non-resolving congoleumplantrust.com host; evaluate the live site’s TLS behavior separately." },
  "eagle-picher-industries-pi-settlement-trust": { trustName: "Eagle-Picher Industries PI Settlement Trust", sourceUrl: "https://www.cpf-inc.com/trusts/epi-trust/", sourceClass: "administrator", retrievalNotes: "Replaces non-resolving legacy host with official CPF EPI trust page." },
  "g-i-holdings-gaf-asbestos-pi-settlement-trust": { trustName: "G-I Holdings (GAF) Asbestos PI Settlement Trust", sourceUrl: "https://www.g-itrust.com/", sourceClass: "official_trust", retrievalNotes: "Replaces non-resolving giasbestostrust.com host with reviewed active trust site." },
  "kaiser-gypsum-asbestos-pi-trust": { trustName: "Kaiser Gypsum Asbestos PI Trust", sourceUrl: "https://www.kaisergypsumtrust.org/", sourceClass: "official_trust", retrievalNotes: "Replaces non-resolving .com host with reviewed official .org trust site." },
  "maremont-asbestos-pi-trust": { trustName: "Maremont Asbestos PI Trust", sourceUrl: "https://maremont.mfrclaims.com/", sourceClass: "administrator", retrievalNotes: "Replaces legacy host that terminates HTTPS; use official administrator portal." },
  "narco-asbestos-trust": { trustName: "NARCO Asbestos Trust", sourceUrl: "https://www.narcoasbestostrust.org/", sourceClass: "official_trust", retrievalNotes: "Replaces non-resolving narcotrust.com host; use browser-compatible retrieval only if direct checks meet a WAF." },
  "ngc-bodily-injury-trust-national-gypsum": { trustName: "NGC Bodily Injury Trust", sourceUrl: "https://www.ngcbitrust.org/", sourceClass: "official_trust", retrievalNotes: "Replaces non-resolving ngcasbestostrust.com host; evaluate TLS behavior on the active site." },
  "owens-corning-fibreboard-asbestos-pi-trust": { trustName: "Owens Corning/Fibreboard Asbestos PI Trust", sourceUrl: "https://www.ocfbasbestostrust.com/", sourceClass: "official_trust", retrievalNotes: "Replaces misspelled ocfasbestostrust.com host; use browser-compatible retrieval only if the active site meets a WAF." },
};
